### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tsuza** [tsuza/mannager-source#1]
- [x] Fix context menu quirks ( #3 )
  - [x] The cursor doesn't correctly change when you hover the gear button. ( #3 )
  - [x] The gear button gets highlighted with the color of the path for no reason. ( #3 )
- [x] Improve the Sourcemod downloading UX by visibly disabling the button. ( #3 )
- [x] Add a stop button when the servers is running. ( #4 )
- [x] Visually separate input & output text in the server terminal ( #5 )
- [x] Add a show / close server terminal button ( #8 )
- [x] Automatically find an available port for the server ( #10 )
   - [ ] Currently it fails if another server within the same process is using the same port. 
- [x] Make the server status clearer by showing a active / inactive label next to the server to see if it's running.
- [x] Add a button that pastes the join link to the clipboard ( #15 )
- [ ] Add a button that automatically makes the server hoster join the server
- [x] #14 ( #13 )
- [ ] #12
- [ ] Finalize support for CS2
- [x] Add other Source1 games such as NMRIH, Half Life 2 DM, and such. ( #6 & #7 )
- [ ] #9
- [ ] Fix the notifications being borked on Gnome 46 unless you specify on_close
- [x] Look into making the server entries draggable so users can change the order. ( #2 )
- [ ] Add options to quickly add admins / convars and such.
- [ ] Add a confirmation pop-up when you delete the server.
- [ ] Add an automatic app updater.
- [ ] Explore [iced_anim](https://github.com/Brady-Simon/iced_anim) for animations
- [x] Properly handle errors.
- [ ] See if implementing servers running through WINE / WSL is feasible.
- [x] Add an edit page for server entries. ( #11 )
- [ ] A plugin downloader.
- [x] #17
